name: Release Firmware

on:
  push:
    tags:
      - 'v*'  # 当推送以 v 开头的标签时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set release tag
        id: set_release_tag
        run: |
          echo "release_tag=$(date +'v%Y.%m.%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Upload Firmware
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: firmware.bin
          path: path/to/firmware.bin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.set_release_tag.outputs.release_tag }}
          generate_release_notes: true
          body: |
            这是自定义的发布说明。
            版本: ${{ steps.set_release_tag.outputs.release_tag }}
          files: |
            path/to/firmware.bin
        env:
          GITHUB_TOKEN: ${{ secrets.serenity_li }}
